<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Демонстрационная версия продукта «1С-Битрикс: Управление сайтом»");
$APPLICATION->SetPageProperty("NOT_SHOW_NAV_CHAIN", "Y");
$APPLICATION->SetTitle("Каталог книг");

include ($_SERVER['DOCUMENT_ROOT'] . SITE_TEMPLATE_PATH . '/winner.php');

?><section class="promo">
<h2 class="promo__title">Нужен стафф для катки?</h2>
<p class="promo__text">
	 На нашем интернет-аукционе ты найдёшь самое эксклюзивное сноубордическое и горнолыжное снаряжение.
</p>
<ul class="promo__list">
	<li class="promo__item promo__item--boards"> <a class="promo__link" href="<?= SITE_TEMPLATE_PATH ?>/boards/">Доски и лыжи</a> </li>
	<li class="promo__item promo__item--attachment"> <a class="promo__link" href="<?= SITE_TEMPLATE_PATH ?>/fixations/">Крепления</a> </li>
	<li class="promo__item promo__item--boots"> <a class="promo__link" href="<?= SITE_TEMPLATE_PATH ?>/boots/">Ботинки</a> </li>
	<li class="promo__item promo__item--clothing"> <a class="promo__link" href="<?= SITE_TEMPLATE_PATH ?>/clothes/">Одежда</a> </li>
	<li class="promo__item promo__item--tools"> <a class="promo__link" href="<?= SITE_TEMPLATE_PATH ?>/instruments/">Инструменты</a> </li>
	<li class="promo__item promo__item--other"> <a class="promo__link" href="<?= SITE_TEMPLATE_PATH ?>/sundry/">Разное</a></li>
</ul>
 </section><section class="lots">
<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"yeti-catalog", 
	array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "yeti-catalog",
		"DETAIL_ACTIVE_DATE_FORMAT" => "",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "TAGS",
			5 => "SORT",
			6 => "PREVIEW_TEXT",
			7 => "PREVIEW_PICTURE",
			8 => "DETAIL_TEXT",
			9 => "DETAIL_PICTURE",
			10 => "DATE_ACTIVE_FROM",
			11 => "ACTIVE_FROM",
			12 => "DATE_ACTIVE_TO",
			13 => "ACTIVE_TO",
			14 => "SHOW_COUNTER",
			15 => "SHOW_COUNTER_START",
			16 => "IBLOCK_TYPE_ID",
			17 => "IBLOCK_ID",
			18 => "IBLOCK_CODE",
			19 => "IBLOCK_NAME",
			20 => "IBLOCK_EXTERNAL_ID",
			21 => "DATE_CREATE",
			22 => "CREATED_BY",
			23 => "CREATED_USER_NAME",
			24 => "TIMESTAMP_X",
			25 => "MODIFIED_BY",
			26 => "USER_NAME",
			27 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "N",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "FINISH_DATE",
			1 => "HISTORY_DATE",
			2 => "HISTORY_PLAYER_ID",
			3 => "PRICE_START",
			4 => "HISTORY_PRICE",
			5 => "PRICE_CURRENT",
			6 => "PRICE_GAP",
			7 => "CATEGORY",
			8 => "MIN_PRICE",
			9 => "PRICE",
			10 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "arrFilter ",
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "8",
		"IBLOCK_TYPE" => "catalog",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"LIST_ACTIVE_DATE_FORMAT" => "",
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "TAGS",
			5 => "SORT",
			6 => "PREVIEW_TEXT",
			7 => "PREVIEW_PICTURE",
			8 => "DETAIL_TEXT",
			9 => "DETAIL_PICTURE",
			10 => "DATE_ACTIVE_FROM",
			11 => "ACTIVE_FROM",
			12 => "DATE_ACTIVE_TO",
			13 => "ACTIVE_TO",
			14 => "SHOW_COUNTER",
			15 => "SHOW_COUNTER_START",
			16 => "IBLOCK_TYPE_ID",
			17 => "IBLOCK_ID",
			18 => "IBLOCK_CODE",
			19 => "IBLOCK_NAME",
			20 => "IBLOCK_EXTERNAL_ID",
			21 => "DATE_CREATE",
			22 => "CREATED_BY",
			23 => "CREATED_USER_NAME",
			24 => "TIMESTAMP_X",
			25 => "MODIFIED_BY",
			26 => "USER_NAME",
			27 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "FINISH_DATE",
			1 => "HISTORY_DATE",
			2 => "HISTORY_PLAYER_ID",
			3 => "PRICE_START",
			4 => "HISTORY_PRICE",
			5 => "PRICE_CURRENT",
			6 => "PRICE_GAP",
			7 => "CATEGORY",
			8 => "MIN_PRICE",
			9 => "PRICE",
			10 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "9",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "yeti-pagination",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "TIMESTAMP_X",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "DESC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"SEF_FOLDER" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => SITE_TEMPLATE_PATH . "/#SECTION_CODE#/",
			"detail" => SITE_TEMPLATE_PATH . "/#SECTION_CODE#/?ELEMENT_ID=#ELEMENT_ID#",
		),
		"VARIABLE_ALIASES" => array(
			"detail" => array(
				"ELEMENT_ID" => "ELEMENT_ID",
			),
		)
	),
	false
);?>
 </section><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>